#
# Copyright (c) 2025 Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V. (represented by Fraunhofer ISST)
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under
# the terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#
{{- if eq (.Chart.Version | trunc 3) "3.0" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-pre-upgrade-delete"
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-hook-sa
      restartPolicy: Never
      containers:
        - name: delete-deployments
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              set -o errexit
              {{- $oldBackendName := "" }}
              {{- if .Values.backend.fullnameOverride }}
                {{- $oldBackendName = .Values.backend.fullnameOverride | trunc 63 | trimSuffix "-" }}
              {{- else }}
                {{- $backendName := default .Chart.Name "backend" .Values.backend.nameOverride }}
                {{- if contains $backendName .Release.Name }}
                  {{- $oldBackendName = .Release.Name | trunc 63 | trimSuffix "-" }}
                {{- else }}
                  {{- $oldBackendName = printf "%s-%s" .Release.Name $backendName | trunc 63 | trimSuffix "-" }}
                {{- end }}
              {{- end }}
              if kubectl get deployment "$oldBackendName" > /dev/null 2>&1; then
                echo "Deleting old deployment with name: $oldBackendName"
                kubectl delete deployment {{ $oldBackendName }}
              else
                echo "Deployment $oldBackendName does not exist. Nothing to delete.
              fi
              {{- $oldFrontendName := "" }}
              {{- if .Values.frontend.fullnameOverride }}
                {{- $oldFrontendName = .Values.frontend.fullnameOverride | trunc 63 | trimSuffix "-" }}
              {{- else }}
                {{- $frontendName := default .Chart.Name "backend" .Values.frontend.nameOverride }}
                {{- if contains $frontendName .Release.Name }}
                  {{- $oldFrontendName = .Release.Name | trunc 63 | trimSuffix "-" }}
                {{- else }}
                  {{- $oldFrontendName = printf "%s-%s" .Release.Name $frontendName | trunc 63 | trimSuffix "-" }}
                {{- end }}
              {{- end }}
              if kubectl get deployment "$oldFrontendName" > /dev/null 2>&1; then
                echo "Deleting old deployment with name: $oldFrontendName"
                kubectl delete deployment {{ $oldFrontendName }}
              else
                echo "Deployment $oldFrontendName does not exist. Nothing to delete.
              fi
{{- end }}
