apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: migration-pvc-supplier-edc
  namespace: product-puris
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi