apiVersion: batch/v1
kind: Job
metadata:
  name: pg-restore-job-puris-supplier
  namespace: product-puris
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: restore
        image: postgres:18
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting restore..."
          pg_restore -h supplier-backend-postgresql -U postgres -d postgres -c --if-exists -1 /migration/db.dump
          echo "Restore complete!"
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: supplier-secret-postgres-init
              key: postgres-password
        volumeMounts:
        - name: storage
          mountPath: /migration
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: migration-pvc-supplier-puris