@startuml
skinparam linetype ortho

package "<<system>> PURIS FOSS Frontend"{

  [Stock View] as stock_view
  [Dashboard] as dashboard
  [Authentication Service] as auth_service
  [Access Service] as access_service

  auth_service <-- access_service

}

[Keycloak] as idp

idp - auth_service

stock_view --> "Stock Interface"
stock_view --> "MAD interface"

dashboard --> "Stock Interface"
dashboard --> "MAD interface"

@enduml
