@startuml
[Data Provisioning & Transformation] as data_prov
[Eclipse DataSpace Components Connector] as edc
[Postgresql DB] as postgres
[Keycloak] as idp

data_prov -( "Interface internal systems"
edc -- "EDC APIs"

package "<<system>> PURIS"{

  [PURIS FOSS Backend] as puris_backend
  [PURIS FOSS Frontend] as puris_frontend

  "EDC APIs" )-- "provide and pull data\naccording to standards" puris_backend
  "Interface internal systems" - puris_backend
  puris_backend <-- puris_frontend
  puris_frontend -- idp
  puris_backend --> postgres

}

@enduml
