@startuml
skinparam linetype polyline
skinparam nodesep 20
skinparam ranksep 50

package "<<system>> PURIS FOSS Frontend"{

  [Stock View] as stock_view
  [Dashboard] as dashboard
  [Authentication Service] as auth_service

}
"Interfaces for\n- Planned Production Output\n- Short-Term Material Demand\n- Delivery Information" -- dashboard
[Keycloak] as idp

idp - auth_service

stock_view --( "Stock Interface"
stock_view --( "MAD interface"

dashboard --( "Stock Interface"
dashboard --( "MAD interface"

@enduml
