@startuml
skinparam linetype ortho

package "<<system>> PURIS FOSS Backend"{

  [DTR] as dtr
  [EDC] as edc
  [Stock] as stock
  [MAD] as mad

  edc - "EDC Client Interface"
  "Registry & Discovery Interfaces" - dtr

  dtr -- "Register and discover twins\n& submodesls" stock
' TODO make look great
  edc -- "query catalog &\nrequest data (via edc)" stock

  mad - "MAD Interface"

}
stock - "Stock Submodel \n& internalInterface"
stock -- mad

@enduml
