@startuml
autonumber
skinparam sequenceMessageAlign center

box "Data Consumer"
participant "Business\nApplication" as app_cons
end box

box "Data Provider"
participant "Business\nApplication" as app_prov
end box


app_cons ->  app_prov: Request Information Object Exchange
note right: Request Endpoint
return Accepted

activate  app_prov
app_prov ->  app_prov: Determine requested Information Object

app_prov ->  app_cons: Send requested Information Object
note left: Response Endpoint
deactivate app_prov
return Accepted

@enduml
