@startuml
skinparam linetype polyline
skinparam nodesep 150
skinparam ranksep 50

() mad_interface as "MAD Interface"
() dtr_interface as "Registry & Discovery Interfaces"
() oauth as "OAuth2"
() edc_interface as "EDC Management API"
() not_interface as "Notification Interface"
() data_interface as "Submodel & internal interface"

package "<<system>> PURIS FOSS Backend"{

  [DTR] as dtr
  [Stock, Production, Demand,\nDelivery, Days of Supply\nInformation] as stock
  [EDC] as edc
  [Notifications] as not
  [MAD] as mad
}

dtr_interface -down- dtr
oauth )-down- dtr

not -up- "use edc for communication" edc

dtr -down- "Register and discover twins\n& submodels" stock
data_interface -down- stock
stock -right- "query catalog &\nget data (via edc)" edc
stock -down- mad
edc -right-( edc_interface

mad -- mad_interface
mad -right- not

not -right- not_interface

@enduml
