@startuml
skinparam linetype polyline
skinparam nodesep 20
skinparam ranksep 50

package "<<system>> PURIS FOSS Frontend"{
  [Authentication Service] as auth_service

  package "User Views" as user_views {
    [Material List View] as material_list_view
    [Material Details View] as material_details_view
    [Notification View] as notifications_view
  }
  package "Admin Views" as admin_views {
    [Import View] as import_view
    [Catalog View] as catalog_view
    [Negotiations View] as negotiations_view
    [Transfer View] as transfer_view
  }
}
[Keycloak] as idp

idp -down- auth_service

auth_service -down--> user_views
auth_service -down--> admin_views


() edc_interface as "EDC Interface"
() mad_interface as "MAD Interface"
() information_interface as "PURIS Information Interface"

material_list_view <--- information_interface
material_details_view <--- information_interface
notifications_view <--- information_interface
material_list_view <--- mad_interface
material_details_view <--- mad_interface
notifications_view <--- mad_interface
import_view <--- mad_interface
import_view <--- information_interface

catalog_view <--- edc_interface
catalog_view <--- mad_interface
negotiations_view <--- edc_interface
transfer_view <--- edc_interface

@enduml
